Update kover to v0.8.0 (#285)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|
--------------------------------------------------------------------------------------
| ------------------ |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
|
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|
|
[org.jetbrains.kotlinx.kover](https://togithub.com/Kotlin/kotlinx-kover)
| `0.7.6` -> `0.8.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlinx.kover/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlinx.kover/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlinx.kover/0.7.6/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlinx.kover/0.7.6/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[org.jetbrains.kotlinx:kover-gradle-plugin](https://togithub.com/Kotlin/kotlinx-kover)
| `0.7.6` -> `0.8.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlinx:kover-gradle-plugin/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlinx:kover-gradle-plugin/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlinx:kover-gradle-plugin/0.7.6/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlinx:kover-gradle-plugin/0.7.6/0.8.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

***

### Release Notes

<details>
<summary>Kotlin/kotlinx-kover (org.jetbrains.kotlinx.kover)</summary>

###
[`v0.8.0`](https://togithub.com/Kotlin/kotlinx-kover/blob/HEAD/CHANGELOG.md#080--2024-05-15)

\===================
This release introduces DSL rework to simplify the work with Android
build variants, adds the possibility of lazy configuration, allows for
the creation of custom report variants, and expands the ability of
reports filtering.

It is incompatible with the previous version, and we provide best-effort
migration assistance as well as the [migration
guide](https://togithub.com/Kotlin/kotlinx-kover/blob/v0.8.0/docs/gradle-plugin/migrations/migration-to-0.8.0.md).

#### Kover Gradle Plugin

##### Features

- [`#461`](https://togithub.com/Kotlin/kotlinx-kover/issues/461)
Implemented DSL revision 4
- [`#410`](https://togithub.com/Kotlin/kotlinx-kover/issues/410) Add
possibility of lazy configuration of Kover extensions
- [`#462`](https://togithub.com/Kotlin/kotlinx-kover/issues/462)
Redesign the concept of default reports
- [`#463`](https://togithub.com/Kotlin/kotlinx-kover/issues/463) Add the
ability to create custom report variants
- [`#338`](https://togithub.com/Kotlin/kotlinx-kover/issues/338) Create
an interface for Kover tasks
- [`#66`](https://togithub.com/Kotlin/kotlinx-kover/issues/66) Added
support for the publishing plugin to Gradle Plugin Portal
- [`#466`](https://togithub.com/Kotlin/kotlinx-kover/issues/466)
Implemented multi-project shortcuts
- [`#339`](https://togithub.com/Kotlin/kotlinx-kover/issues/339)
Implemented warn on verification error
- [`#572`](https://togithub.com/Kotlin/kotlinx-kover/issues/572) Added
DslMarker to Kover public interfaces
- [`#570`](https://togithub.com/Kotlin/kotlinx-kover/issues/570) Added
overload for functions of KoverVariantCreateConfig
- [`#590`](https://togithub.com/Kotlin/kotlinx-kover/issues/590) Expose
reportDir property in KoverHtmlReport interface
- [`#587`](https://togithub.com/Kotlin/kotlinx-kover/issues/587) Added
property variantName to KoverReport interface
- [`#584`](https://togithub.com/Kotlin/kotlinx-kover/issues/584) Added
project filter for reports
- [`#274`](https://togithub.com/Kotlin/kotlinx-kover/issues/274) Allow
for classes to be Included by annotation
- [`#454`](https://togithub.com/Kotlin/kotlinx-kover/issues/454) Added a
report filter by parent class or interface

##### Bugfixes

- [`#557`](https://togithub.com/Kotlin/kotlinx-kover/issues/557) Changed
log level for print coverage task
- [`#520`](https://togithub.com/Kotlin/kotlinx-kover/issues/520) Fixed
error: Kover requires extension with name 'androidComponents'

##### Internal features

- [`#567`](https://togithub.com/Kotlin/kotlinx-kover/issues/567) Used
compile dependency to Kover Features in Kover Gradle Plugin

##### Documentation

- [`#531`](https://togithub.com/Kotlin/kotlinx-kover/issues/531) Added
explanations about applying of the plugin
- [`#486`](https://togithub.com/Kotlin/kotlinx-kover/issues/486)
Increased the readability of the Kover documentation

#### Kover JVM Agent

##### Features

- [`#464`](https://togithub.com/Kotlin/kotlinx-kover/issues/464)
Repacked the intellij-agent artifact to kover-jvm-agent

##### Bugfixes

- [`#583`](https://togithub.com/Kotlin/kotlinx-kover/issues/583)
Excluded from report companion objects with only constants
- [`#548`](https://togithub.com/Kotlin/kotlinx-kover/issues/548) Fixed
coverage drop in case of using different classloaders for same class

#### Changelog relative to version `0.8.0-Beta2`

##### Kover Gradle Plugin

##### Features

- [`#590`](https://togithub.com/Kotlin/kotlinx-kover/issues/590) Expose
reportDir property in KoverHtmlReport interface
- [`#587`](https://togithub.com/Kotlin/kotlinx-kover/issues/587) Added
property variantName to KoverReport interface
- [`#584`](https://togithub.com/Kotlin/kotlinx-kover/issues/584) Added
project filter for reports
- [`#274`](https://togithub.com/Kotlin/kotlinx-kover/issues/274) Allow
for classes to be Included by annotation
- [`#454`](https://togithub.com/Kotlin/kotlinx-kover/issues/454) Added a
report filter by parent class or interface

##### Documentation

- [`#486`](https://togithub.com/Kotlin/kotlinx-kover/issues/486)
Increased the readability of the Kover documentation for 0.8.0

##### Kover JVM Agent

##### Bugfixes

- [`#583`](https://togithub.com/Kotlin/kotlinx-kover/issues/583)
Excluded from report companion objects with only constants
- [`#548`](https://togithub.com/Kotlin/kotlinx-kover/issues/548) Fixed
coverage drop in case of using different classloaders for same class

</details>

***

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

***

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

***

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/WhosNickDoglio/dagger-rules).


<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4zNjMuNSIsInVwZGF0ZWRJblZlciI6IjM3LjM2My41IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

<!-- branch-stack -->

- `main`
  - \#285 :point\_left:

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>